version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    groups:
      storybook:
        patterns:
        - "@storybook*"
        update-types:
        - "minor"
        - "patch"
      playwright:
        patterns:
        - "@playwright*"
        update-types:
        - "minor"
        - "patch"
