/**
 * Copyright 2023 Mia srl
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { useCallback, useMemo } from 'react'
import { message } from 'antd'

import { FeedbackMessage } from '../components/FeedbackMessage'
import { FeedbackMessageProps } from '../components/FeedbackMessage/FeedbackMessage.props'

type MessageType = 'loading' | 'info' | 'success' | 'warning' | 'error'

type MessageHook = {
  contextHolder: React.ReactElement<unknown, string | React.JSXElementConstructor<unknown>>
  dismiss: (key: string) => void
  loading: (props: FeedbackMessageProps) => void
  info: (props: FeedbackMessageProps) => void
  success: (props: FeedbackMessageProps) => void
  error: (props: FeedbackMessageProps) => void
  warning: (props: FeedbackMessageProps) => void
}

/**
 * A hook to access the current theme from the context.
 *
 * @returns {MessageHook} The current theme.
 */
const useMessage = (): MessageHook => {
  const [messageApi, contextHolder] = message.useMessage()

  // TODO: Should I keep to use FeedbackMessageProps?
  const open = useCallback((type: MessageType, props: FeedbackMessageProps): void => {
    // TODO: Check if message is of type node
    // TODO: Autogenerated key?
    messageApi.open({
      content: <FeedbackMessage extra={props.extra} key={props.key} message={props.message} />,
      duration: 0,
      style: { display: 'flex' },
      type,
      key: props.key,
    })
  }, [messageApi])

  const dismiss = useCallback((key: string) => { messageApi.destroy(key) }, [messageApi])

  const loading = useCallback((props: FeedbackMessageProps) => { open('loading', props) }, [open])
  const info = useCallback((props: FeedbackMessageProps) => { open('info', props) }, [open])
  const success = useCallback((props: FeedbackMessageProps) => { open('success', props) }, [open])
  const error = useCallback((props: FeedbackMessageProps) => { open('error', props) }, [open])
  const warning = useCallback((props: FeedbackMessageProps) => { open('warning', props) }, [open])

  return useMemo(() => ({
    contextHolder,
    dismiss,
    loading,
    info,
    success,
    error,
    warning,
  }), [contextHolder, dismiss, error, info, loading, success, warning])
}

export default useMessage


// const hook = useMessage()

// hook.loading({ message: 'Sto caricando', key: 'commit_save' })

// if (isCommitCompleted) {
//     hook.success({ message: 'Ho caricato', extra: (<Button>OK</Button>) key='commit_save' })
// }
